version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    image: my_airflow_image
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
      - _AIRFLOW_WWW_USER_FIRSTNAME=FirstName
      - _AIRFLOW_WWW_USER_LASTNAME=LastName
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=misecretkey
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=airflowprueba@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=lsjcnybimzqjczhg
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=airflowprueba@gmail.com
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname FirstName --lastname LastName --role Admin --email admin@example.com && airflow scheduler & airflow webserver"

  scheduler:
    image: my_airflow_image
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=misecretkey
    volumes:
      - ./dags:/opt/airflow/dags
    command: bash -c "airflow db upgrade && airflow scheduler"
    

volumes:
  postgres_data:
